kind: pipeline
type: docker
name: default

steps:
  - name: dco
    image: algernon/drone-plugin-dco
    depends_on: [ clone ]

  - name: signature-check
    image: algernon/drone-plugin-signature-check
    keys: [ 10E65DC045EABEFCC5193A26AC1E90BAC433F68F ]
    depends_on: [ clone ]
    when:
      event: tag

  - name: cache-restore
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./lib
    depends_on: [ clone ]

  - name: bootstrap
    image: registry.madhouse-project.org/algernon/drone-language:arduino
    pull: always
    depends_on: [ cache-restore ]
    commands:
      - (cd lib/hardware/keyboardio/avr/libraries/Kaleidoscope; git restore src)
      - make setup
      - sed -i 's,typedef BootKeyboardWrapper BootKeyboard;,,' lib/hardware/keyboardio/avr/libraries/Kaleidoscope/src/kaleidoscope/driver/hid/keyboardio/Keyboard.h

  - name: cache-rebuild
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./lib
    depends_on: [ bootstrap ]

  - name: build
    image: registry.madhouse-project.org/algernon/drone-language:arduino
    pull: always
    depends_on: [ bootstrap ]
    commands:
      - make build OUTPUT_DIR=output/${DRONE_BUILD_NUMBER}

  - name: upload
    image: registry.madhouse-project.org/algernon/drone-language:arduino
    depends_on: [ build ]
    environment:
      CEC_TOKEN:
        from_secret: CEC_TOKEN
      CEC_URL:
        from_secret: CEC_URL
      CEC_PATH:
        from_secret: CEC_PATH
    commands:
      - curl -sLo cec https://download.pydio.com/latest/cells-client/release/%7Blatest%7D/linux-amd64/cec
      - chmod +x cec
      - tools/upload ${DRONE_BUILD_NUMBER}

volumes:
  - name: cache
    host:
      path: /tmp/cache/model01-sketch

image_pull_secrets:
  - registry_madhouse_project_org
