kind: pipeline
type: docker
name: default

steps:
  - name: dco
    image: algernon/drone-plugin-dco
    depends_on: [ clone ]

  - name: signature-check
    image: algernon/drone-plugin-signature-check
    keys: [ 10E65DC045EABEFCC5193A26AC1E90BAC433F68F ]
    depends_on: [ clone ]
    when:
      event: tag

  - name: cache-restore
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./lib
    depends_on: [ clone ]

  - name: bootstrap
    image: registry.madhouse-project.org/algernon/drone-language:arduino
    pull: always
    depends_on: [ cache-restore ]
    commands:
      - make setup

  - name: cache-rebuild
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./lib
    depends_on: [ bootstrap ]

  - name: build
    image: registry.madhouse-project.org/algernon/drone-language:arduino
    pull: always
    depends_on: [ bootstrap ]
    commands:
      - make build

volumes:
  - name: cache
    host:
      path: /tmp/cache/model01-sketch

image_pull_secrets:
  - registry_madhouse_project_org
