kind: pipeline
type: docker
name: default

steps:
  - name: dco
    image: algernon/drone-plugin-dco
    depends_on: [ clone ]

  - name: signature-check
    image: algernon/drone-plugin-signature-check
    keys: [ 10E65DC045EABEFCC5193A26AC1E90BAC433F68F ]
    depends_on: [ clone ]
    when:
      event: tag

  - name: cache-restore
    image: drillster/drone-volume-cache
    depends_on: [ clone ]
    restore: true
    mount:
      - lib
    volumes:
      - /tmp/cache/Model01-Sketch:/cache

  - name: bootstrap
    image: algernon/drone-language:arduino
    pull: always
    depends_on: [ cache-restore ]
    commands:
      - make setup

  - name: cache-rebuild
    image: drillster/drone-volume-cache
    rebuild: true
    depends_on: [ bootstrap ]
    mount:
      - lib
    volumes:
      - /tmp/cache/Model01-Sketch:/cache

  - name: build
    image: algernon/drone-language:arduino
    pull: always
    depends_on: [ bootstrap ]
    commands:
      - make build
